### PR TITLE
Remove glog from vendor

### PR DESCRIPTION
**Pull request by jarrpa**
Signed-off-by: Jose A. Rivera <jarrpa@redhat.com>

### CODE REVIEW

**Comment by msau42** [comment]
Looks like we need to update some pkgs to remove the glog dependency from vendor

**Comment by jarrpa** [comment]
@msau42 Packages updated. As a consequence, I had to remove some code that (erroneously, I believe) was trying to register the CSIDriver CRD. I imagine this is legacy behavior we don't want to be doing anymore.

**Pull request merged**
