### PR TITLE
Document function details.

### PR DESCRIPTION
**Pull request by humblec**
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Comment by msau42** [comment]
The entire connection pkg is being moved to csi-lib-utils: https://github.com/kubernetes-csi/csi-lib-utils/pull/8

**Comment by humblec** [comment]
> The entire connection pkg is being moved to csi-lib-utils: [kubernetes-csi/csi-lib-utils#8](https://github.com/kubernetes-csi/csi-lib-utils/pull/8)

Oh..ok. thanks @msau42 !

**Comment by vladimirvivien** [comment]
@humblec should this be closed ?

**Review by vladimirvivien — COMMENTED** [review]
LGTM

**Comment by vladimirvivien** [comment]
@humblec should this be closed ?

**Pull request closed without merging**
