### PR TITLE
 Use protosanitizer when logging

### PR DESCRIPTION
**Pull request by lpabon**

### CODE REVIEW

**Comment by pohly** [comment]
The number of imported files in this PR and in `vendor` in general would be a lot smaller if pruning was enabled in the repo - see https://github.com/kubernetes-csi/drivers/pull/127.

I know it's unrelated to this PR, but perhaps you can add it here anyway?

**Comment by lpabon** [comment]
Great idea @pohly. Result: +459 −1,718,522 lines

**Comment by msau42** [comment]
@lpabon can you also cherry pick to release 1.0

**Comment by msau42** [comment]
xref: https://github.com/kubernetes-csi/external-provisioner/issues/82

**Pull request merged**
